ERROR - 2024-06-25 03:14:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'password_baru', 'sig', 3306, '', 0)
#1 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\sig\sig\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\sig\sig\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\sig\sig\system\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
#6 C:\xampp\htdocs\sig\sig\app\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
#7 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(941): App\Controllers\Dashboard->index()
#8 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#9 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\sig\sig\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\sig\sig\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\sig\sig\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\sig\sig\system\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
#5 C:\xampp\htdocs\sig\sig\app\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
#6 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(941): App\Controllers\Dashboard->index()
#7 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#8 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sig\sig\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-06-25 03:14:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `kabupaten`
WHERE `kabupaten`.`id_kabupaten` = :kabupaten.id_kabupaten:', [...], false)
 3 SYSTEMPATH\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
 5 APPPATH\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-25 03:18:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'password_baru', 'sig', 3306, '', 0)
#1 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\sig\sig\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\sig\sig\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\sig\sig\system\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
#6 C:\xampp\htdocs\sig\sig\app\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
#7 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(941): App\Controllers\Dashboard->index()
#8 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#9 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\sig\sig\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\sig\sig\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\sig\sig\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\sig\sig\system\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
#5 C:\xampp\htdocs\sig\sig\app\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
#6 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(941): App\Controllers\Dashboard->index()
#7 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#8 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sig\sig\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-06-25 03:18:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `kabupaten`
WHERE `kabupaten`.`id_kabupaten` = :kabupaten.id_kabupaten:', [...], false)
 3 SYSTEMPATH\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
 5 APPPATH\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-25 05:03:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'password_baru', 'sig', 3306, '', 0)
#1 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\sig\sig\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\sig\sig\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\sig\sig\system\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
#6 C:\xampp\htdocs\sig\sig\app\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
#7 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(941): App\Controllers\Dashboard->index()
#8 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#9 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\sig\sig\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\sig\sig\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\sig\sig\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\sig\sig\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\sig\sig\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\sig\sig\system\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
#5 C:\xampp\htdocs\sig\sig\app\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
#6 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(941): App\Controllers\Dashboard->index()
#7 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#8 C:\xampp\htdocs\sig\sig\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sig\sig\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-06-25 05:03:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `kabupaten`
WHERE `kabupaten`.`id_kabupaten` = :kabupaten.id_kabupaten:', [...], false)
 3 SYSTEMPATH\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(577): CodeIgniter\Model->doFind(true, 1)
 5 APPPATH\Controllers\Dashboard.php(17): CodeIgniter\BaseModel->find(1)
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
